import { TextField } from "@/components";
import { useAuth } from "@/hooks/useAuth";
import { Form, Formik } from "formik";
import Head from "next/head";
import Image from "next/image";
import React, { useState } from "react";
import * as Yup from "yup";

const Auth = () => {
  const [auth, setAuth] = useState<"signup" | "signin">("signin");
  const { error, isLoading, logOut, signIn, signUp, user, setIsLoading } =
    useAuth();

  const toggleAuth = (state: "signup" | "signin") => {
    setAuth(state);
  };

  const onSubmit = async (formData: { email: string; password: string }) => {
    if (auth === "signup") {
      signUp(formData.email, formData.password);
    } else {
      signIn(formData.email, formData.password);
    }
  };

  const validation = Yup.object({
    email: Yup.string()
      .email("Enter valid email")
      .required("Email is required"),
    password: Yup.string()
      .min(6, "6 minimum character")
      .required("Password is requried"),
  });

  return (
    <div className="relative flex h-screen w-screen flex-col bg-black md:items-center md:justify-center md:bg-transparent">
      <Head>
        <title>Auth</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta />
        <link rel="icon" href="/logo.svg" />
      </Head>

      <Image
        src={"https://bit.ly/3JaHcJU"}
        alt={"bg"}
        fill
        className="z-10 !hidden object-cover opacity-10 sm:!inline"
      />

      <Image
        src={"/logo.svg"}
        alt={"logo"}
        width={70}
        height={70}
        className={"absolute left-4 top-4 cursor-pointer object-contain"}
      />
      <div className="relative z-10 mt-24 space-y-8 rounded bg-black/75 px-6 py-10 md:mt-0 md:max-w-md md:px-10">
        <h1 className="text-4xl font-semibold">
          {" "}
          {auth === "signup" ? "Sign Up" : "Sign In"}
        </h1>
        {error && (
          <p className="text-center font-semibold text-red-500">{error}</p>
        )}
        <Formik
          initialValues={{ email: "", password: "" }}
          onSubmit={onSubmit}
          validationSchema={validation}
        >
          <Form>
            <div className="space-y-4">
              <TextField name="email" placeholder="Email" type="text" />
              <TextField
                name="password"
                placeholder="Password"
                type="password"
              />
            </div>

            <button
              type="submit"
              disabled={isLoading}
              className="mt-4 w-full rounded bg-[#E10856] py-3 font-semibold"
            >
              {isLoading
                ? "Loading..."
                : auth === "signin"
                  ? "Sign In"
                  : "Sign Up"}
            </button>
          </Form>
        </Formik>

        {auth === "signin" ? (
          <div className="text-[gray]">
            Not yet account?{" "}
            <button
              type="button"
              className="text-white hover:underline"
              onClick={() => toggleAuth("signup")}
            >
              Sign Up Now
            </button>
          </div>
        ) : (
          <div className="text-[gray]">
            Already have account?{" "}
            <button
              type="button"
              className="text-white hover:underline"
              onClick={() => toggleAuth("signin")}
            >
              Sign In
            </button>
          </div>
        )}
      </div>
    </div>
  );
};

export default Auth;
